scale and 1code comparison
humb1t/1code-rust pull request #1
Opened 2020-03-02 17:47 UTC by eadventurous

Initially implemented through **nightly bench**, then changed to **bencher** for compatability with @humb1t implementation.

**speed benchmarks:** `cargo bench`
**size benchmarks:** `cargo test size -- --nocapture`

2020-03-02 17:57 UTC, eadventurous commented
The `StructToSerialize` changed, floating point and hashmap values removed, for compatibility with `parity_scale_codec`

2020-03-04 12:58 UTC, humb1t requested changes

2020-03-04 12:58 UTC, humb1t commented on Cargo.toml
> +parity-scale-codec = {version = "1.1.2", features = ["derive"] }
Please, move them to `dev-deps` - we don't need them for actual 1-code logic

2020-03-04 12:58 UTC, humb1t commented on src/lib.rs
> +pub mod test_struct;
please remove this module and move content inside tests, even if it means code duplication

2020-03-04 12:58 UTC, humb1t commented on src/lib.rs
> +mod size_cmp;
Only business related modules should be defined in root lib

2020-03-04 12:58 UTC, humb1t commented on src/size_cmp.rs
> +}
move to /tests/

2020-03-04 13:48 UTC, humb1t requested changes

2020-03-04 13:48 UTC, humb1t commented on benches/tests.rs
> +pub fn get_test_struct() -> StructToSerialize{
Let's replace it with `StructToSerialize::new()` function in `impl StructToSerialize`

2020-03-04 13:48 UTC, humb1t commented on benches/tests.rs
> +#[derive(serde::Serialize, Debug, PartialEq, Encode)]
Replace `Encode` with `parity_scale_codec::Encode` - it will be easier to read and we use it only here.

2020-03-04 13:48 UTC, humb1t commented on benches/tests.rs
> +    let struct_to_serialize = get_test_struct();
After implementation of a `::new()` we will see the real type here:
`let struct_to_serialize = StructToSerialize::new()`

2020-03-05 07:19 UTC, humb1t approved these changes

2020-03-05 07:19 UTC, merged